### ISSUE TITLE
Using Spark.halt() does not work as intended

### ISSUE THREAD

**Issue by Artuto** [lamarios/sparknotation#7]
Basically, when using Spark.halt() to stop a request, Spark throws an exception (spark.HaltException) and handles it gracefully.

Sparknotation however, causes the request to error with code 500 and an exception in the console:

```
17:25:52.100 [qtp653261558-24] INFO  com.ftpix.sparknnotation.Sparknotation - Params [spark.Request@62b256cf, spark.Response@244972ca]
17:25:58.435 [qtp653261558-24] ERROR spark.http.matching.GeneralError - 
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.ftpix.sparknnotation.Sparknotation.beforeAfterContent(Sparknotation.java:347) ~[sparknotation-1.13.jar:?]
	at com.ftpix.sparknnotation.Sparknotation.lambda$createBefore$25(Sparknotation.java:280) ~[sparknotation-1.13.jar:?]
	at spark.FilterImpl$1.handle(FilterImpl.java:73) ~[spark-core-2.9.3.jar:?]
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48) ~[spark-core-2.9.3.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:133) ~[spark-core-2.9.3.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[spark-core-2.9.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: spark.HaltException
```

**Comment by lamarios** [comment]
Good catch ! The fix is available in version 1.14 whenever the maven central propagation is done.

**Comment by Artuto** [comment]
After testing, it still happens on 1.14

**Comment by lamarios** [comment]
Hmmm I made a small application to test here https://github.com/lamarios/sparknotation-halt-test

http://localhost:4567/default and http://localhost:4567/sparknotation

Both halts behave the same way.

**Comment by Artuto** [comment]
I'm doing it like this:

```java
    @SparkBefore("*")
    public void checkAuthenticated(@SparkHeader("Authorization") String token)
    {
       halt(403, "Forbidden");
    }
```

And getting the following error:

```
22:52:05.421 [qtp1901078157-17] INFO  com.ftpix.sparknnotation.Sparknotation - class java.lang.String
22:52:05.422 [qtp1901078157-17] INFO  com.ftpix.sparknnotation.Sparknotation - Param of type class java.lang.String has SparkHeader annotation with value [Authorization]
22:52:05.424 [qtp1901078157-17] INFO  com.ftpix.sparknnotation.Sparknotation - Params [null]
22:52:05.433 [qtp1901078157-17] ERROR spark.http.matching.GeneralError - 
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.ftpix.sparknnotation.Sparknotation.beforeAfterContent(Sparknotation.java:347) ~[sparknotation-1.14.jar:?]
	at com.ftpix.sparknnotation.Sparknotation.lambda$createBefore$25(Sparknotation.java:280) ~[sparknotation-1.14.jar:?]
	at spark.FilterImpl$1.handle(FilterImpl.java:73) ~[spark-core-2.9.2.jar:?]
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48) ~[spark-core-2.9.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:133) ~[spark-core-2.9.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[spark-core-2.9.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: spark.HaltException
```

**Comment by lamarios** [comment]
Ok, 1.15 is on the way. Need to wait for maven central propagation and it should be working.

**Comment by Artuto** [comment]
That worked, thanks!
